[package]
name = "acadctl"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
acadctl-lisp = { path = "../lisp" }
acadctl-rpc = { path = "../rpc" }
bytes.workspace = true
clap.workspace = true
futures-util.workspace = true
tokio = { workspace = true, features = ["signal"] }
tonic.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
libc.workspace = true
objc2.workspace = true
objc2-app-kit.workspace = true
sysinfo.workspace = true

[target.'cfg(windows)'.dependencies]
sysinfo.workspace = true
windows-sys.workspace = true
