(defun acadctl:_drive-execution (/ acadctl:continue acadctl:staged-form)
  (while (setq acadctl:continue (acadctl:_advance-execution))
    (setq acadctl:staged-form (read acadctl:*staged-form*))
    (eval acadctl:staged-form))
  (setq acadctl:*staged-form* nil)
  (princ))
