[package]
name = "acadctl-rpc"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bytes.workspace = true
camino.workspace = true
futures-util.workspace = true
hyper-util.workspace = true
prost.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
tower.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2-foundation.workspace = true

[build-dependencies]
protoc-bin-vendored.workspace = true
tonic-prost-build.workspace = true
